config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  
  get '/:locale', to: 'home#index', as: 'root_locale', :format => false, defaults: { locale: 'bg' }
  root to: "home#index", defaults: { locale: 'bg' }
  get '/bg', to: 'home#index', locale: 'bg'
  get '/en', to: 'home#index', locale: 'en'

  scope "(:locale)", locale: /en|bg/ do
    resources :forms
    resources :tickets
    resources :contacts
    get '/:friendly_id', to: 'static_pages#show', as: 'static_page', :format => false
    get 'offers/:friendly_id', to: 'offers#show', as: 'offer', :format => false, defaults: { locale: 'bg' }
  end

  post '/tinymce_assets', to: 'tinymce_assets#create'
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :set_locale

  helper_method :generate_job_fair_link

  def index
    @static_pages_headers = StaticPage.where(in_slider: true)
    @yellow_box_text = Settings.where(setting_name: 'HP yellow box text').first
    @purple_box_text = Settings.where(setting_name: 'HP purple box text').first
    @jobs_fletcher_lynd_link = Settings.where(setting_name: 'Jobs Fletcher Lynd link').first
    @first_white_box = Settings.where(setting_name: 'HP first white box text').first
    @second_white_box = Settings.where(setting_name: 'HP second white box text').first
    @online_job_fair = Settings.where(setting_name: 'Online job fair').first
    @after_job_fair_text = Settings.where(setting_name: 'HP after online job fair box text').first
    @contacts_slider = Settings.where(setting_name: 'HP slider contact information').first
    @offers = Offer.where(visible: true).order(offer_order: :asc)
  end

  def generate_job_fair_link
    if @online_job_fair.present?
      locale = params[:locale] || 'bg'
      slug = @online_job_fair.setting.gsub('<p>', '').gsub('</p>', '')
      "#{locale}/#{slug}"
    end
  end
end

app/views/home/index.html.haml
%section.banner-slider
	%ul.bxslider
		- if @static_pages_headers.present?
			- @static_pages_headers.each do |sph|
				-if sph.banner.present?
					%li
						%a{href: "#{static_page_path(friendly_id: sph.slug)}"}
							= image_tag sph.banner.full
							%div.slide
								%h1= sph.banner_caption
								%p= sph.banner_description
		%li
			%a{href: "#{new_form_path}"}
				= image_tag 'zapishi-se-online.jpg'
				.slide
					%h1= t(:apply_online)
		%li
			%a{href: "#{new_ticket_path}"}
				= image_tag 'samoletni-bileti.jpg'
				.slide
					%h1= t(:ticket_form)
		%li
			%a{href: "#"}
				= image_tag 'contacts.png'
				.slide.slide-last
					%h1= t(:contacts)
					= @contacts_slider.setting.html_safe if @contacts_slider.present?
%section.info-banner
	%div
		= @yellow_box_text.setting.html_safe if @yellow_box_text.present?
	%div
		= link_to image_tag('logo-InterExchange.png'), 'http://interexchange.org'
	%div
		= @purple_box_text.setting.html_safe if @yellow_box_text.present?
	%div
		= @jobs_fletcher_lynd_link.setting.gsub('<p>', '').gsub('</p>', '').html_safe if @jobs_fletcher_lynd_link.present?
	%div
		= @first_white_box.setting.html_safe if @first_white_box.present?
		= @second_white_box.setting.html_safe if @second_white_box.present?
%section.info-grid
	-if @offers.present?
		- @offers.each do |of| 
			.single-grid
				- if of.banner.present?
					= link_to image_tag(of.banner.thumb), offer_path(friendly_id: of.friendly_id, locale: params[:locale])
				- else
					= link_to image_tag('blank_thumb.jpg'), offer_path(friendly_id: of.friendly_id, locale: params[:locale])
				%p
					%span= link_to of.title, offer_path(friendly_id: of.friendly_id, locale: params[:locale])
					%br
					= strip_tags of.locations
				%div
					= of.description.html_safe
.info-online
	= link_to image_tag('skype.png'), generate_job_fair_link
	= @after_job_fair_text.setting.html_safe if @after_job_fair_text.present?
.banner-button
	%div
		= link_to t(:yellow_banner), new_form_path
	%div
		= link_to t(:green_banner), generate_prices_and_terms_link