config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  
  get '/:locale', to: 'home#index', as: 'root_locale', :format => false, defaults: { locale: 'bg' }
  root to: "home#index", defaults: { locale: 'bg' }
  get '/bg', to: 'home#index', locale: 'bg'
  get '/en', to: 'home#index', locale: 'en'

  scope "(:locale)", locale: /en|bg/ do
    resources :forms
    resources :tickets
    resources :contacts
    get '/:friendly_id', to: 'static_pages#show', as: 'static_page', :format => false
    get 'offers/:friendly_id', to: 'offers#show', as: 'offer', :format => false, defaults: { locale: 'bg' }
  end

  post '/tinymce_assets', to: 'tinymce_assets#create'
end

app/models/contact.rb
class Contact < ActiveRecord::Base

	apply_simple_captcha

	validates_each :email do |record, attr, value|
    	record.errors.add(attr, I18n.t(:invalidemail)) unless value =~ /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i
  	end

	validates :names, presence: true
	validates :message, presence: true
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
	before_action :set_locale

	def new
		@formd = Settings.where(setting_name: 'Contact form description').first
		@contact = Contact.new
	end

	def create
		@formd = Settings.where(setting_name: 'Contact form description').first
		@contact = Contact.new(form_params)

		if @contact.valid_with_captcha?
			@contact.save
			FormMailer.contact_email(@contact).deliver
			flash[:notice] = t(:contact_form_success)
			redirect_to root_path
		else
			render 'new'
		end
	end

	private 
	def form_params
		params.require(:contact).permit(:names, :email, :message, :captcha, :captcha_key, :captcha, :captcha_key)
	end
end

app/views/contacts/new.html.erb
<div class="banner">
	<%= image_tag "form_header.jpg" %>
</div>
<div class="content">	
	<h1><%= t(:contact_form) %></h1>
	<%= @formd.setting.html_safe if @formd.present? %>
	<%= form_for @contact, url: contacts_path do |f| %>
		<% if @contact.errors.any? %>
			<ul>
				<% @contact.errors.full_messages.each do |msg| %>
				<li class="error-message"><%= msg %></li>
				<% end %>
			</ul>
		<% end %>
		<p>&nbsp;</p>
		<div class=".clearfix"></div>
</div>
<div class="form">
	<div>
		<p>
			<%= f.label t(:names) %><br/>
			<%= f.text_field :names %><br/>
		</p>
		<p>
			<%= f.label t(:email) %><br/>
			<%= f.text_field :email %><br/>
		</p>
		<p>
			<%= f.label t(:message) %><br/>
			<%= f.text_field :message %><br/>
		</p>
	</div>
	<%= show_simple_captcha(:object=>"contact") %>
	<div class="submit">
		<%= f.submit t(:submit_form), id: "submit-button" %>
	</div>
</div>
<% end %>