config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  
  get '/:locale', to: 'home#index', as: 'root_locale', :format => false, defaults: { locale: 'bg' }
  root to: "home#index", defaults: { locale: 'bg' }
  get '/bg', to: 'home#index', locale: 'bg'
  get '/en', to: 'home#index', locale: 'en'

  scope "(:locale)", locale: /en|bg/ do
    resources :forms
    resources :tickets
    resources :contacts
    get '/:friendly_id', to: 'static_pages#show', as: 'static_page', :format => false
    get 'offers/:friendly_id', to: 'offers#show', as: 'offer', :format => false, defaults: { locale: 'bg' }
  end

  post '/tinymce_assets', to: 'tinymce_assets#create'
end

app/controllers/forms_controller.rb
class FormsController < ApplicationController
	before_action :set_locale

	def new
		@formd = Settings.where(setting_name: 'Application form description').first
		@universities = University.all
		@form = Form.new
	end

	def create
		@universities = University.all
		@formd = Settings.where(setting_name: 'Application form description').first
		@form = Form.new(form_params)

		if @form.valid_with_captcha?
			@form.save
			FormMailer.application_email(@form).deliver
			FormMailer.application_email_to_employee(@form).deliver
			redirect_to root_path
		else
			render 'new'
		end
	end

	private 
	def form_params
		params.require(:form).permit(:last_name, :first_name, :fathers_name, :birthday, :place_of_birth, :mobile, :skype, :university_id, :year_of_study, :email, :fletcher_office, :wandt, :selfarranged, :captcha, :captcha_key)
	end
end

app/views/forms/new.html.erb
<div class="banner">
	<%= image_tag "zapishi-se-online.jpg" %>
</div>
<div class="content">	
	<h1><%= t(:app_form) %></h1>
	<p><%= @formd.setting.html_safe if @formd.present? %></p>
	<%= form_for @form, url: forms_path do |f| %>
		<% if @form.errors.any? %>
			<ul>
				<% @form.errors.full_messages.each do |msg| %>
				<li class="error-message"><%= msg %></li>
				<% end %>
			</ul>
		<% end %>
</div>
<div class="form">
	<div>
		<p>
			<%= f.label t(:first_name) %><br/>
			<%= f.text_field :first_name %><br/>
		</p>
		<p>
			<%= f.label t(:fathers_name) %><br/>
			<%= f.text_field :fathers_name %><br/>
		</p>
		<p>
			<%= f.label t(:last_name) %><br/>
			<%= f.text_field :last_name %><br/>
		</p>
		<p class="date" style="width: 370px;">
			<%= f.label t(:birthday) %><br/>
			<%= date_select :form, :birthday, start_year: Time.now.year - 35, end_year: Time.now.year - 18 %><br/>
		</p>
		<p>
			<%= f.label t(:place_of_birth) %><br/>
			<%= f.text_field :place_of_birth %><br/>
		</p>
	</div>
	<div>
		<p>
			<%= f.label t(:mobile) %><br/>
			<%= f.text_field :mobile %><br/>
		</p>
		<p>	
			<%= f.label t(:skype) %><br/>
			<%= f.text_field :skype %><br/>
		</p>
	</div>
	<div>
		<p>
			<%= f.label t(:university) %><br/>
			<%= collection_select(:form, :university_id, @universities, :id, :name, prompt: true) %><br/>
		</p>
		<p>
			<%= f.label t(:year_of_study) %><br/>
			<%= select "form", "year_of_study", [ ["1", "1"], ["2", "2"], ["3", "3"], ["4", "4"], ["5", "5"], ["6", "6"], ["master 1", "master 1"], ["master 2", "master 2"], ["master 3", "master 3"], ["master 4", "master 4"], ] %><br/>
		</p>
	</div>
	<div>
		<p>
			<%= f.label t(:email) %><br/>
			<%= f.text_field :email %><br/>
		</p>
	</div>
	<div>
		<p>
			<%= f.label t(:fletcher_office) %><br/>
			<%= select "form", "fletcher_office", [[ "Sofia", "Sofia" ], [ "Blagoevgrad", "Blagoevgrad" ]] %><br/>
		</p>
	</div>
	<div>
		<p>
			<%= f.label t(:wandt) %>
			<%= f.check_box :wandt %>
		</p>
		<p>
			<%= f.label t(:selfarranged) %>
			<%= f.check_box :selfarranged %><br/>
		</p>
	</div>
	<%= show_simple_captcha(:object=>"form") %>
	<div class="submit">
		<%= f.submit "Submit", id: "submit-button" %>
	</div>
</div>
<% end %>

app/views/forms/old.html.haml
- form_for @form, url: forms_path do |f|
	= if @form.errors.any?
		= pluralize(@form.errors.count 'error')
		'prohibited this form from being saved'
		%ul
			- @form.errors.full_messages.each do |msg|
				%li 
					= msg
	= f.label :last_name
	= f.text_field :last_name
	= f.label :first_name
	= f.text_field :first_name
	= f.label :fathers_name
	= f.text_field :fathers_name
	= f.label :birthday
	= f.text_field :birthday
	= f.label :place_of_birth
	= f.text_field :place_of_birth
	= f.label :mobile
	= f.text_field :mobile
	= f.label :skype
	= f.text_field :skype
	= f.label :university
	= f.text_field :university
	= f.label :year_of_study
	= f.text_field :year_of_study
	= f.label :email
	= f.text_field :email
	= f.label :fletcher_office
	= f.text_field :fletcher_office
	= f.submit