config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  
  get '/:locale', to: 'home#index', as: 'root_locale', :format => false, defaults: { locale: 'bg' }
  root to: "home#index", defaults: { locale: 'bg' }
  get '/bg', to: 'home#index', locale: 'bg'
  get '/en', to: 'home#index', locale: 'en'

  scope "(:locale)", locale: /en|bg/ do
    resources :forms
    resources :tickets
    resources :contacts
    get '/:friendly_id', to: 'static_pages#show', as: 'static_page', :format => false
    get 'offers/:friendly_id', to: 'offers#show', as: 'offer', :format => false, defaults: { locale: 'bg' }
  end

  post '/tinymce_assets', to: 'tinymce_assets#create'
end

app/views/layouts/_footer.html.haml
.logo-bottom
	= link_to image_tag('logo-bottom.png'), 'http://fletcherlynd.com'

%script
	(function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
	(i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
	m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
	})(window,document,'script','//www.google-analytics.com/analytics.js','ga');

	ga('create', 'UA-26981080-1', 'auto');
	ga('send', 'pageview');

app/views/layouts/_head.html.haml
%head
    %meta{:charset => "utf-8"}
    %title Fletcher Lynd - Work and Travel
    %meta{:content => "user-scalable=no, initial-scale=1, maximum-scale=1, minimum-scale=1, width=device-width, height=device-height, target-densitydpi=device-dpi", :name => "viewport"}
    %meta{:content => "", :name => "Fletcher Lynd - Work and Travel"}
    %meta{:content => "", :name => "BetaSve.com"}

    / Le HTML5 shim, for IE6-8 support of HTML5 elements
    /[if lt IE 9]
    = favicon_link_tag 'favicon.ico'
    = javascript_include_tag "https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js", "https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js"

    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags

app/views/layouts/application.html.haml
!!!
%html
  = render 'layouts/head'
  %body
    %header      
      .clearfix
        - if params[:locale] == 'bg'
          - replace_root_path = root_locale_path('bg')
        -else
          - replace_root_path = root_locale_path('en')
        = link_to(image_tag("logo.png"), replace_root_path, class: 'logo')
        %a#menuButton
          &nbsp;
        .rightMenu
          %a{href:"mailto:info@fletcherlynd.com"}
          %a
            &nbsp;
          %a
            &nbsp;
          %div
            = link_to "EN", root_locale_path('en')
            |
            = link_to "BG", root_locale_path('bg')
        %nav#menu
          %ul
            - @pages.each_with_index do |page, k|
              = link_to page.title, static_page_path(friendly_id: page.slug), id: "#{page.slug}" if page.in_main_menu
              = link_to t(:apply_online), new_form_path, id: 'forms' if k == 2
              = link_to t(:ticket_form), new_ticket_path, id: 'tickets' if k == 3
            = link_to t(:contacts), new_contact_path, id: 'contacts'

  - flash.each do |name, msg|
    .space
    = content_tag :div, :class => "alert alert-#{name == :error ? "danger" : "success" } alert-dismissable" do
      %button.close{:type => "button", :data => {:dismiss => "alert"}, :aria => {:hidden => "true"} } &times;
      %p
        = msg
  = yield
  = render 'layouts/footer'

app/views/layouts/old_application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Fletcher</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>

<%= yield %>

</body>
</html>